[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qclef-2025-clustering"
version = "0.1"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["src"]
