hdbscan_gmm_clustering:
  min_cluster_size: 5
  min_samples: null
  cluster_selection_method: 'leaf'
  cluster_selection_epsilon: 0.2
  covariance_type: 'full'
  n_init: 10
  metric: 'euclidean'
  random_state: 42