classical_clustering:
  metric: 'euclidean'
  k_range: [75]
  random_state: 42

quantum_kmedoids:
  use_quantum: false
  use_hybrid: false
  gamma: 1
  gamma_constraint: 8
  random_state: 42

# Configuration for second-stage classical clustering (alternative to annealing)
second_stage_clustering:
  enabled: true  # Controls whether to use second-stage clustering when annealing is false
  k_range: [10, 25, 50]  # Possible final cluster sizes for second-stage
  metric: 'euclidean'
  random_state: 42