classical_clustering:
  metric: 'euclidean'
  k_range: [75]
  random_state: 42

quantum_clustering:
  k_range: [50]

quantum_kmedoids:
  use_quantum: true
  use_hybrid: false
  gamma: 1
  gamma_constraint: 10
  random_state: 42