general:
  reduction: False
classical_clustering:
  metric: 'euclidean'
  k_range: [80, 100, 125, 150]
  random_state: 42

quantum_clustering:
  k_range: [75]

quantum_kmedoids:
  use_quantum: false
  use_hybrid: false
  gamma: 1
  gamma_constraint: 8
  random_state: 42